## NumPy Arrays

In [3]:
import numpy as np

Creating a simple array

In [18]:
array = np.array([1, 2, 3, 4, 5, 6])
print(array)
print(type(array))
print(array.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


Creating a multi-dimensional array

In [20]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(array)
print(array.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [28]:
array = np.array([[1, 2, 3, 0], [4, 5, 6, 0], [7, 8, 9, 0]])
print(array)
print(array.shape)

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
(3, 4)


NumPy Helper Methods

In [40]:
# zeros()
array = np.zeros((3, 3), dtype=int)
print(array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [42]:
# ones()
array = np.ones((3, 3), dtype=int)
print(array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [46]:
# full()
array = np.full((3, 3), 7, dtype=int)
print(array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [60]:
# random.random()
array = np.random.random((3, 3))
print(array)

[[0.17694038 0.65055185 0.49860915]
 [0.62047358 0.98290533 0.69616294]
 [0.59897636 0.8676172  0.01610793]]


In [74]:
# random.randint(range, )
array = np.random.randint(1, 9, (3, 3))   # in range 1 and 9
print(array)

[[6 7 5]
 [3 5 8]
 [6 3 4]]


In [82]:
# accessing the number at the [row_index, col_index] position
print(array[0, 0])
print(array[1, 2])
print(array[2, 0])
# in lists: listl[i][i]  and  arrays: array[i, i]

6
8
6


In [90]:
# using a comparison operator
print(array > 2)
print("-----------")
print(array % 2 == 0)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-----------
[[ True False False]
 [False False  True]
 [ True False  True]]


In [98]:
# as you can see, istead of accessing each element and using the operator, 
# you can just use the array name and define the operator, it will compute itself within the array elements

In [110]:
# boolean indexing
print(array[array > 5])
# this will show only the array elements which are higher than 5

[6 7 8 6]


### Array Computational Functions

In [113]:
array = np.array([2.1, 3.9, 5.5, 11.8, 15.7, 13.3])
print(array)

[ 2.1  3.9  5.5 11.8 15.7 13.3]


In [121]:
# sum()
print(np.sum(array))

52.3


In [129]:
# floor() 
print(np.floor(array))

[ 2.  3.  5. 11. 15. 13.]


In [131]:
# ceil()
print(np.ceil(array))

[ 3.  4.  6. 12. 16. 14.]


In [133]:
# round()
print(np.round(array))

[ 2.  4.  6. 12. 16. 13.]


### Performing Arithmetic Operations Between Numbers and Arrays

In [137]:
first_array = np.array([111, 333, 555])
second_array = np.array([222, 444, 666])

In [139]:
print(first_array + second_array)

[ 333  777 1221]


In [141]:
print(first_array + 1)
print(second_array * 2)

[112 334 556]
[ 444  888 1332]


### Unit conversion (length)

In [145]:
feet = np.array([1, 2, 3, 4, 5])

In [151]:
cm = feet * 30.48
inch = feet * 12
meter = feet * 0.3048
yard = feet * 0.3333
print(cm)
print(inch)
print(meter)
print(yard)

[ 30.48  60.96  91.44 121.92 152.4 ]
[12 24 36 48 60]
[0.3048 0.6096 0.9144 1.2192 1.524 ]
[0.3333 0.6666 0.9999 1.3332 1.6665]


In [155]:
random_3d_array = np.random.randint(1, 9, (3, 3))

In [157]:
print(random_3d_array)

[[7 5 7]
 [1 3 5]
 [5 6 1]]


In [159]:
# now lets perform some operations on this: by *3
multpl_by_3 = random_3d_array * 3
print(multpl_by_3)

[[21 15 21]
 [ 3  9 15]
 [15 18  3]]


In [163]:
# as you can see from here, np.array itself accessed to each array element and performed computation.
# no need to write extra code to specify indexes and perform operations